#!/usr/bin/env bash

if [[ $# -eq 3 && $1 == ?* && -d $2 ]]
then
	for v in "$2"/*.$1
	do
		video="${v##*/}"
		video="${video%.*}"

		if [[ ! -d "$3" ]]
		then
			mkdir -p "$3"
		fi

		echo
		echo -e "\033[33mTranscoding ${video}.${1}...\033[0m"
		ffmpeg -loglevel quiet -stats -i "${v}" -c:v libx264 -crf 23 -c:a libfaac -q:a 100 "${3}/${video}.mp4"
	done
	echo
	echo -e '\033[32mTranscode Complete!\033[0m'
else
	echo -n "\033[31musage: ${0} <targetExtension> <inputDirectory> <outputDirectory>\033[0m"
	exit 1
fi