#!/usr/bin/env bash

if [[ $# -ge 2 ]]
then
  _target_codec='libx265'

  if [[ "$1" =~ ^(h\.?)?(26[45])$ ]]
  then
    _target_codec="libx${BASH_REMATCH[2]}"

    shift
  fi

  # Next command line argument is the destination directory
  readonly DESTINATION_DIRECTORY=$1

  # Advance to next command line argument
  shift

  if [[ $# -eq 0 ]]
  then
    echo -e "\033[33mNo input files specified\033[0m"

    exit 1
  fi

  # Remaining command line arguments are input video files
  _videos=( "$@" )

  for _video in "${_videos[@]}"
  do
    _video_name="${_video##*/}"              # Extract file name from path
    _video_name_out="${_video_name%.*}.mp4"  # Remove extension from file name

    if [[ ! -f "$_video" ]]
    then
      echo -e "\033[31mNot a file, skipping:\033[0m ${_video_name}"

      continue
    fi

    # If the destination exists and is not a directory
    if [[ -e "$DESTINATION_DIRECTORY" && ! -d "$DESTINATION_DIRECTORY" ]]
    then
      echo -e "\e[35mError:\e[0m ${DESTINATION_DIRECTORY} is not a directory"
      exit 1
    else
      mkdir -p "$DESTINATION_DIRECTORY"
    fi

    echo -en "\n\e[33mTranscoding\e[0m ${_video_name} "

    # Convert input file(s) to mp4
    case $_target_codec in
      'libx265')
        echo "using h.265 encoder..."
        ffmpeg -loglevel panic -stats -nostdin -i "$_video" -map 0 -c copy -tag:v hvc1 -c:v libx265 -x265-params log-level=error -crf 28 -c:a aac -c:s mov_text "${DESTINATION_DIRECTORY}/${_video_name_out}"
        ;;

      'libx264')
        echo "using h.264 encoder..."
        ffmpeg -loglevel panic -stats -nostdin -i "$_video"  -map 0 -c copy -c:v libx264 -crf 23 -c:a aac -q:a 100 "${DESTINATION_DIRECTORY}/${_video_name_out}"
        ;;

      *)
        echo -e "\033[31mTranscoding cancelled. No encoder for\033[0m ${_video_name}"
        ;;
    esac
  done

  echo -e '\n\033[32mTranscode Complete!\e[0m'
else
  echo -e "\e[33mUsage:\e[0m ${0##*/} [<output_codec=265|264>] <output_directory> <input_file> [...]"
  exit 1
fi

