#!/usr/bin/env bash

if [[ $# -ge 2 && $1 == ?* ]]
then
  # First command line argument is the destination directory
  _dest_dir=$1

  # Skip first command line argument
  shift

  # Remaining command line arguments are input video files
  _videos=( "$@" )

  for _video in "${_videos[@]}"
  do
    _video_name="${_video##*/}"      # Extract file name from path
    _video_stem="${_video_name%.*}"  # Remove extension from file name

    # If the destination exists and is not a directory
    if [[ -e "$_dest_dir" && ! -d "$_dest_dir" ]]
    then
      echo -e "\e[35mError:\e[0m ${_dest_dir} is not a directory"
      exit 1
    else
      mkdir -p "$_dest_dir"
    fi

    echo -e "\n\e[33mTranscoding\e[0m ${_video_name}..."

    # Convert input to mp4
    ffmpeg -loglevel panic -stats -nostdin -i "${_video}" -c:v libx264 -crf 23 -c:a aac -q:a 100 "${_dest_dir}/${_video_stem}.mp4"
  done
  echo
  echo -e '\e[32mTranscode Complete!\e[0m'
else
  echo -e "\e[35mUsage:\e[0m ${0##*/} <outputDirectory> <inputFile> [...]"
  exit 1
fi

